# Generated by Django 5.1 on 2024-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('birth_place', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('mail', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('registration_address', models.CharField(max_length=250)),
                ('residence_address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
