# Generated by Django 5.1 on 2024-08-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_birth_place_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
